#include <stdio.h>
#include <stdlib.h>

/* I am not familiar with manipulating binary, this code is generated by
chatgpt, will have to come back later */

unsigned rightrot(unsigned x, int n) {
  // Get the total number of bits in an unsigned integer
  int total_bits = sizeof(x) * 8;

  // Shift x to the right by n positions
  unsigned shifted_x = x >> n;

  // Get the rightmost n bits of x and shift them to the leftmost positions
  unsigned right_bits = x << (total_bits - n);

  // Combine the shifted x and the rightmost n bits
  return shifted_x | right_bits;
}

int main(void) {
  unsigned x = 0b10101010; // Binary representation of 170
  int n = 3;               // Rotate to the right by 3 positions

  x = rightrot(x, n);
  printf("X = %u\n", x); // Output the result in decimal
  return EXIT_SUCCESS;
}
