#include <stdio.h>
#include <stdlib.h>

/* I am not familiar with manipulating binary, this code is generated by
chatgpt, will have to come back later */

unsigned setbits(unsigned x, int p, int n, unsigned y) {
  unsigned mask = ((1U << n) - 1)
                  << (p - n + 1); // Create mask for the n bits at position p
  unsigned y_bits =
      (y & ((1U << n) - 1))
      << (p - n + 1); // Extract rightmost n bits from y and shift to position p
  return (x & ~mask) | y_bits; // Clear the bits in x at position p and insert
                               // the new bits from y
}

int main(void) {
  unsigned x = 0b10101010;
  unsigned y = 0b11001100;
  int p = 5, n = 3;

  x = setbits(x, p, n, y);
  printf("X = %u", x);
  return EXIT_SUCCESS;
}
